version: "3.4"
networks:
  default:
    external:
      name: ${NETWORK}
configs:
  gateway_config:
    file: nginx.conf
  gateway_server_app_config:
    file: ${NGINX_SERVER_APP_CONFIG}
services:
  gateway:
    image: nginx:1.13.0-alpine
    configs:
    - source: gateway_config
      target: /etc/nginx/nginx.conf
      mode: 0444
    - source: gateway_server_app_config
      target: /etc/nginx/server_app.conf
      mode: 0444
    ports:
    - ${GATEWAY_PORT}:80
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 2
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 20s
        max_attempts: 5
        window: 20s
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: pause
        monitor: 20s
        max_failure_ratio: 0.1
      resources:
        limits:
          cpus: ${GATEWAY_LIMIT_CPU}
          memory: ${GATEWAY_LIMIT_MEMORY}
  app:
    image: ${APP_IMAGE}
    environment:
      - INSTANCE_ID="{{.Task.Slot}}"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 2
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: ${APP_REPLICAS}
      restart_policy:
        condition: any
        delay: 20s
        max_attempts: 5
        window: 10s
      update_config:
        parallelism: 0
        delay: 1s
        failure_action: pause
        monitor: 10s
        max_failure_ratio: 0.1
      resources:
        limits:
          cpus: ${APP_LIMIT_CPU}
          memory: ${APP_LIMIT_MEMORY}
